config/routes.rb
Talk::Application.routes.draw do

  root to: "dashboards#show"

  resources :users, only: [] do
    resources :contacts, only: [:create]
  end

  resources :contacts, only: [] do
    resources :conversations, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      resources :contacts, only: [:index]
    end
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :frequency, inclusion: { in: (1..365) }
  validates :frequency, numericality: true
  validates :frequency, numericality: { only_integer: true }
  validates :frequency, presence: true
  validates :name, presence: true
  validates :name, uniqueness: { scope: :user_id }
  validates :user_id, presence: true

  has_many :conversations
  belongs_to :user                  

  def last_conversation_days_ago
    unless last_conversation.created_at == 0
      seconds = Time.now.utc - last_conversation.created_at.utc
      days = seconds / (60 * 60 * 24)
      days.round
    else
      0
    end
  end

  def goal_percentage
    100 - ((last_conversation_days_ago.to_f / frequency) * 100).round
  end

  private

  def last_conversation
    conversations.order("created_at DESC").limit(1).first || NoConversation.new
  end
end

class NoConversation
  def created_at
    Time.now
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  validates :contact_id, presence: true

  belongs_to :contact
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :contacts

  def overall_percentage
    if contacts.present?
      raw_overall_percentage.round
    else
      100
    end
  end

  private

  def raw_overall_percentage
    contacts.map(&:goal_percentage).inject(:+) / contacts.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
    @contact = current_user.contacts.new(contact_params)
    if @contact.save
      flash[:notice] = "Yah! We've added #{@contact.name}."
      redirect_to root_path
    else
      render "dashboards/show"
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :frequency)
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def create
    contact = current_user.contacts.find(params[:contact_id])
    conversation = contact.conversations.new
    if conversation.save
      flash[:notice] = "We got it!"
    else
      flash[:error] = "Whoops, something went wrong"
    end

    redirect_to root_path
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authorize

  def show
    @contact = Contact.new
    @contacts = current_user.contacts.sort_by(&:goal_percentage)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/contacts/_contact.html.erb
<section class='contact'>
  <aside class='contact-name'><%= contact.name %></aside>
  <article>
    <span class='contact-goal-percentage'><%= contact.goal_percentage %></span>
    <span class='contact-frequency'><%= contact.frequency %></span>
    <span class='contact-last-conversation'>
      <%= "#{contact.last_conversation_days_ago} days ago" %>
    </span>
    <%= render 'contacts/record_conversation.html.erb', contact: contact %>
  </article>
</section>

app/views/contacts/_form.html.erb
<%= form_for @contact, method: :post, url: user_contacts_path(current_user) do |form| %>
  <% if @contact.errors.any? %>
    <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %>
      <% end %>
    </ul>
  <% end %>

  <%= form.label :name, 'Name' %>
  <%= form.text_field :name %>

  <%= form.label :frequency, 'Frequency' %>
  <%= select_tag("contact[frequency]",
                 options_for_select([
                                      ['Daily', 1],
                                      ['Weekly', 7],
                                      ['Monthly', 30],
                                      ['Annually', 365]
                                    ])) %>

  <%= form.submit 'Add' %>
<% end %>

app/views/contacts/_record_conversation.html.erb
<span class='record-conversation'>
  <%= link_to 'We spoke today',
      contact_conversations_path(contact.id),
      method: 'POST' %>
</span>

app/views/dashboards/show.html.erb
<h1>Your Contacts</h1>

<div class='overall-percentage'>
  <h2>Overall Progress: </h2>
  <h2 id='overall-percentage-value'>
    <%= current_user.overall_percentage %>
  </h2>
</div>

<div class='contacts-list'>
  <%= render partial: 'contacts/contact', collection: @contacts %>
</div>

<%= render 'contacts/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id='header'>
    <% if signed_in? -%>
      <%= link_to t('.sign_out'), sign_out_path, :method => :delete %>
    <% else -%>
      <%= link_to t('.sign_in'), sign_in_path %>
    <% end -%>
  </div>

  <div id='flash'>
    <% flash.each do |key, value| -%>
      <div id='flash_<%= key %>'><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<div class='text-field'>
  <%= form.label :email %>
  <%= form.text_field :email, :type => 'email' %>
</div>

<div class='password-field'>
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id='clearance' class='sign-up'>
  <h2><%= t('.title') %></h2>

  <%= form_for @user do |form| %>
    <%= render :partial => '/users/form', :object => form %>

    <div class='submit-field'>
      <%= form.submit %>
    </div>

    <div class='other-links'>
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>
  <% end %>
</div>